# Generated by Django 3.1.4 on 2021-03-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210325_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Name',
        ),
    ]
