# Generated by Django 3.1.4 on 2021-03-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_billuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billuser',
            name='Name',
        ),
    ]
